### PR TITLE
Resolved memory leak

### PR DESCRIPTION
**Pull request by bwall**
I was running into an issue of memory leaking when using this module.  It appears that the primary culprit (although Valgrind still identifies some smaller leaks currently) is when env_emu_new is called, there are no corresponding env_emu_free function calls.  I have updated this is the Cython code, and regenerated it.

I do plan on checking out the other memory leaks in the near future, but this PR handles one which can make this module quickly fill the RAM of lighter devices if continually called.

### CODE REVIEW

**Comment by buffer** [comment]
Thanks! Really appreciated!

**Comment by buffer** [comment]
I reverted the pull request because I am experiencing some segfaults while executing the tests. Can you please run them locally? (move to tests directory and run sctest.py -s 0) I would like to understand if it depends on your patch or on the new version on Cython.

**Comment by buffer** [comment]
Seems like it happens even after reverting the patch so it should be a Cython issue.

**Comment by buffer** [comment]
Feel free to resubmit the patch. The bug is not related to it. Thanks.

**Comment by bwall** [comment]
Will do :)

**Pull request merged**
